# Generated by Django 5.1.2 on 2024-11-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FormApp", "0002_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Memo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=5)),
                ("memo", models.CharField(max_length=255)),
            ],
        ),
    ]
